name: Build and Publish Rocks to GHCR

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 */14 * *" # Trigger every 2 weeks at midnight UTC

jobs:

  tag-rocks:
    uses: ./.github/workflows/tag-rocks.yaml

  build:
    needs: [tag-rocks]
    strategy:
      matrix:
        rock: ${{ fromJSON(needs.tag-rocks.outputs.json_result) }}
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
    with:
      rock-repo: ${{ github.repository }}
      rock-repo-commit: main
      rockfile-directory: ${{ matrix.rock.location }}
      oci-archive-name: ${{ matrix.rock.name }}_${{ matrix.rock.tag }}
      arch-map: '{"amd64": ["ubuntu-latest"], "arm64": ["ubuntu-24.04-arm"]}'

  test:
    needs: [tag-rocks, build]
    strategy:
      matrix:
        rock: ${{ fromJSON(needs.tag-rocks.outputs.json_result) }}
    uses: canonical/oci-factory/.github/workflows/Test-Rock.yaml@main
    with:
      oci-archive-name: ${{ matrix.rock.name }}_${{ matrix.rock.tag }}

  upload:
    needs: [tag-rocks, test]
    strategy:
      matrix:
        rock: ${{ fromJSON(needs.tag-rocks.outputs.json_result) }}
    runs-on: ubuntu-latest
    steps:

      - name: Upload Rock to GHCR
        uses: canonical/oci-factory/.github/actions/upload-rock@main
        with:
          artifact_name: ${{ matrix.rock.name }}_${{ matrix.rock.tag }}
          tags: ${{ matrix.rock.tag }}
          name: ${{ github.repository }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}